[project]
name = "dashboard"
version = "0.1.0"
requires-python = "<3.14,>=3.13"
dependencies = [
    "bokeh>=3.8.1",
    "jupyter-server-proxy>=4.4.0",
    "numpy>=2.3.4",
    "polars>=1.35.2",
]

[dependency-groups]
dev = []
